// This file is based on a file from https://github.com/PowerShell/PowerShell, and
// edited to use public API's where possible. While not generated, the comment below
// is included to exclude it from StyleCop analysis.
// <auto-generated/>

namespace EditorServicesCommandSuite.Inference
{
    /// <summary>
    /// Enum describing permissions to use runtime evaluation during type inference.
    /// </summary>
    internal enum TypeInferenceRuntimePermissions
    {
        /// <summary>
        /// No runtime use is allowed.
        /// </summary>
        None = 0,

        /// <summary>
        /// Use of SafeExprEvaluator visitor is allowed.
        /// </summary>
        AllowSafeEval = 1,
    }
}
